// packages/react/src/private/HostProvider.tsx
import React, { createContext } from "react";
import type { HostContextValues } from "@leanjs/core";
import type { HostProviderProps } from "../types";
import { RuntimeProvider } from "../core";

export const HostContext = createContext<HostContextValues | undefined>(
  undefined
);

export const HostProvider = ({
  children,
  runtime,
  origin,
}: HostProviderProps) => (
  <HostContext.Provider value={{ origin }}>
    <RuntimeProvider isSelfHosted={false} runtime={runtime}>
      {children}
    </RuntimeProvider>
  </HostContext.Provider>
);

// packages/nuxt/src/HostProvider.vue
<template>
  <slot />
</template>

<script setup lang="ts">
  import { defineProps, provide } from 'vue';
  import type { Runtime } from '@leanjs/core';
  
  export interface HostProviderProps<BaseRuntime extends Runtime = Runtime> {
    origin: string;
    runtime: BaseRuntime;
  }

  const props = defineProps<HostProviderProps>();
  
  provide('origin', props.origin);
  provide('runtime', props.runtime);

</script>
